[package]
name = "rustprelude"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.27", features = ["derive"] }
ignore = "0.4.23"
tempfile = "3.16.0"
clipboard = "0.5"
log = "0.4.25"
env_logger = "0.11.6"
